name: irblaster_controller
description: IR Remote App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies: {}

flutter:
  uses-material-design: true
  assets:
    - assets/switch.json
